In [8]:
import cv2
import numpy as np
import torch
from ultralytics import YOLO
import matplotlib.pyplot as plt
import os

class DetectLineAndSignal:
    def __init__(self, dataset_path, output_path):
        """
        Initialize detector with dataset and output paths
        
        Args:
            dataset_path: Path to dataset.yaml file
            output_path: Directory to save trained model
        """
        self.dataset_path = dataset_path
        self.output_path = output_path
        self.model = None
    
    def train_model(self, model_path):
        """
        Train YOLO model
        
        Args:
            model_path: Path to pretrained YOLO model (e.g., 'yolov8n.pt')
        Returns:
            Training results
        """
        # Initialize model
        self.model = YOLO(model_path)
        
        # Train model
        results = self.model.train(
            data=str(self.dataset_path),
            epochs=50,
            imgsz=640,
            batch=10,
            device='0',
            workers=8
        )
        
        return results
    
    def save_model(self):
        """
        Save trained model to output directory
        """
        # Check if model exists
        if self.model is None:
            raise ValueError("No model to save. Please train the model first.")
            
        # Create output directory if it doesn't exist
        os.makedirs(self.output_path, exist_ok=True)
        
        # Save model
        model_path = os.path.join(self.output_path, "trained_model.pt")
        self.model.save(model_path)
        print(f"Model saved to: {model_path}")
        
    def predict(self, image_path):
        """
        Make predictions on new image
        
        Args:
            image_path: Path to image file
        Returns:
            Prediction results
        """
        if self.model is None:
            raise ValueError("No model available. Please train or load a model first.")
            
        return self.model.predict(image_path)









# Example usage
# if __name__ == "__main__":
#     # Initialize detector
#     detector = DetectLineAndSignal(
#         dataset_path="path/to/dataset.yaml",
#         output_path="./saved_models"
#     )
#     
#     # Train model
#     results = detector.train_model("yolov8n.pt")
#     
#     # Save trained model
#     detector.save_model()
#     
#     # Make predictions
#     predictions = detector.predict("path/to/test/image.jpg")

In [12]:
import os

# 检查目录是否存在
if not os.path.exists("datasets/datasets_hw"):
    print("目录不存在")

In [13]:
    # Initialize detector
    # detector = DetectLineAndSignal(
    #     dataset_path=r"D:\GitHub\yolo_homework\datasets_hw",
    #     output_path="./"
    # )
    # 
    # # Train model
    # results = detector.train_model("yolov8n.pt")
    # # 
    # # # Save trained model
    # detector.save_model()

    # Make predictions
    #predictions = detector.predict("path/to/test/image.jpg")
    model = YOLO("yolov8n.pt")
    model = model.train(data="./datasets_hw/",epochs=50, batch=16, device='0' )

New https://pypi.org/project/ultralytics/8.3.40 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.39  Python-3.12.3 torch-2.3.1 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)
engine\trainer: task=detect, mode=train, model=yolov8n.pt, data=./datasets_hw/, epochs=50, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=train35, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_fram

RuntimeError: Dataset 'datasets_hw' error  [Errno 13] Permission denied: './datasets_hw/'

In [5]:
import cv2
from ultralytics import YOLO

class SignDetector:
    def __init__(self, model_path):
        """
        Initialize detector with trained model
        Args:
            model_path: Path to trained YOLO model (.pt file)
        """
        self.model = YOLO(model_path)
        
    def detect_and_draw(self, image_path, conf_threshold=0.25):
        """
        Detect traffic signs and draw bounding boxes
        Args:
            image_path: Path to input image
            conf_threshold: Confidence threshold for detection
        """
        # Read image
        image = cv2.imread(image_path)
        if image is None:
            raise ValueError("Could not read image")
            
        # Run detection
        results = self.model.predict(
            source=image_path,
            conf=conf_threshold,
            save=True  # 保存结果到runs/detect/predict文件夹
        )[0]
        
        # Process results
        boxes = results.boxes.cpu().numpy()
        
        # Draw on image
        for box in boxes:
            # Get box coordinates
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            
            # Get confidence and class
            confidence = float(box.conf[0])
            class_id = int(box.cls[0])
            
            # Draw rectangle
            cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
            
            # Add label
            label = f"Class {class_id}: {confidence:.2f}"
            cv2.putText(image, label, (x1, y1-10), 
                       cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
        
        return image
        
    def save_result(self, image, output_path):
        """Save annotated image"""
        cv2.imwrite(output_path, image)

In [16]:
# detector = SignDetector("./trained_model.pt")
#     
# # Detect and draw
# image_path = "./img.jpg"
# output_path = "output.jpg"
# 
# result_image = detector.detect_and_draw(image_path)
# detector.save_result(result_image, output_path)
detector = YOLO("./trained_model.pt")
predictions = detector.predict("./img2.jpg")
print(predictions)


image 1/1 D:\GitHub\yolo_homework\img2.jpg: 640x608 (no detections), 77.5ms
Speed: 7.6ms preprocess, 77.5ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 608)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'class_0', 1: 'class_1', 2: 'class_2', 3: 'class_3', 4: 'class_4', 5: 'class_5', 6: 'class_6', 7: 'class_7', 8: 'class_8', 9: 'class_9', 10: 'class_10', 11: 'class_11', 12: 'class_12', 13: 'class_13', 14: 'class_14', 15: 'class_15', 16: 'class_16', 17: 'class_17', 18: 'class_18', 19: 'class_19', 20: 'class_20', 21: 'class_21', 22: 'class_22', 23: 'class_23', 24: 'class_24', 25: 'class_25', 26: 'class_26', 27: 'class_27', 28: 'class_28', 29: 'class_29', 30: 'class_30', 31: 'class_31', 32: 'class_32', 33: 'class_33', 34: 'class_34', 35: 'class_35', 36: 'class_36', 37: 'class_37', 38: 'class_38', 39: 'class_39', 40: 'class_40', 41: 'class_41', 42: 'class_42'}
obb: None
orig

In [25]:
import cv2
import numpy as np
import torch
from ultralytics import YOLO
import matplotlib.pyplot as plt

def detect_line(image):
    # 读取和处理图像的代码保持不变...
    #image = cv2.imread(image_path)
    height, width = image.shape[:2]
    
    # 定义感兴趣区域的顶点
    # 这里我们创建一个梯形区域，这个区域通常包含了车道线的主要部分
    roi_vertices = np.array([
        # 左下角
        [width * 0, height],
        # 左上角
        [width * 0, height * 0.25],
        # 右上角
        [width * 0.9, height * 0.25],
        # 右下角
        [width * 1, height]
    ], dtype=np.int32)
     # 创建ROI掩码
    roi_mask = np.zeros_like(image)
    cv2.fillPoly(roi_mask, [roi_vertices], (255, 255, 255))
    
    # 1. 颜色检测部分
    # 转换到HSV空间
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    
    # 白色阈值（调整饱和度范围来处理反光）
    white_lower = np.array([0, 0, 200])
    white_upper = np.array([180, 40, 240])
    
    # 黄色阈值
    yellow_lower = np.array([15, 80, 80])
    yellow_upper = np.array([45, 255, 255])
    
    # 创建颜色掩码
    white_mask = cv2.inRange(hsv, white_lower, white_upper)
    yellow_mask = cv2.inRange(hsv, yellow_lower, yellow_upper)
    color_mask = cv2.bitwise_or(white_mask, yellow_mask)
    
    # 2. 边缘检测部分
    # 转换到灰度图
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # 使用高斯模糊减少噪声
    blurred = cv2.GaussianBlur(gray, (7, 7), 0)
    
    # Canny边缘检测
    # 使用较低的阈值来检测更多的边缘
    edges = cv2.Canny(blurred, 50, 150)  # More selective thresholds
    
    # 3. 组合颜色检测和边缘检测的结果
    # 使用形态学操作来加强边缘连接
    kernel = np.ones((3,3), np.uint8)
    dilated_edges = cv2.dilate(edges, kernel, iterations=1)
    

    # 计算边缘强度图
    sobelx = cv2.Sobel(gray, cv2.CV_64F, 1, 0, ksize=3)
    sobely = cv2.Sobel(gray, cv2.CV_64F, 0, 1, ksize=3)
    edge_magnitude = np.sqrt(sobelx**2 + sobely**2)
    
    # 设定边缘强度阈值
    edge_threshold = np.mean(edge_magnitude) * 1.5
    strong_edges = (edge_magnitude > edge_threshold).astype(np.uint8) * 255
    
    # 将强边缘与 Canny 边缘结合
    final_edges = cv2.bitwise_and(edges, strong_edges)
        
    #将颜色掩码和边缘检测结果相与
    combined_mask = cv2.bitwise_and(color_mask,final_edges)
    
    # 应用ROI掩码
    final_mask = cv2.bitwise_and(combined_mask, roi_mask[:,:,0])
    # 然后再进行霍夫变换
    lines = cv2.HoughLinesP(
        final_mask,
        rho=1,
        theta=np.pi/180,
        threshold=50,
        minLineLength=25,
        maxLineGap=40
    )
        
    # 创建结果图像
    result = image.copy()
    
    # 在绘制检测到的直线之前添加以下代码
    # if lines is not None:
    #     filtered_lines = []
    #     for line in lines:
    #         x1, y1, x2, y2 = line[0]
    #         # 计算线段角度
    #         angle = abs(np.arctan2(y2 - y1, x2 - x1) * 180 / np.pi)
    #         
    #         # 筛选接近垂直的线条（可以调整角度范围）
    #         # 车道线通常在20-70度之间
    #         if (20 <= angle <= 70) or (110 <= angle <= 160):
    #             filtered_lines.append(line)
    #     
    #     # 使用筛选后的线条绘制
    #     for line in filtered_lines:
    #         x1, y1, x2, y2 = line[0]
    #         cv2.line(result, (x1, y1), (x2, y2), (0, 0, 255), 2)
        
    # 绘制检测到的直线
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            print(line)
            cv2.line(result, (x1, y1), (x2, y2), (0, 255, 0), 1)
    if result is None:
        print("警告：生成的结果图像为空")
        return None
        
    # 确保图像是uint8类型
    if result.dtype != np.uint8:
        result = result.astype(np.uint8)
        
    # 确保图像是BGR格式（OpenCV需要的格式）
    if len(result.shape) != 3 or result.shape[2] != 3:
        print("警告：输出图像格式不正确")
        return None
        
    # 在返回之前进行验证
    try:
        # 测试是否可以编码为视频帧
        _, test_encode = cv2.imencode('.jpg', result)
        if not test_encode.any():
            print("警告：图像编码测试失败")
            return None
    except Exception as e:
        print(f"警告：图像处理出错 - {e}")
        return None

    # # 显示处理过程
    # plt.figure(figsize=(15, 10))
    # 
    # plt.subplot(2, 3, 1)
    # plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    # plt.title('原始图像')
    # 
    # plt.subplot(2, 3, 2)
    # plt.imshow(color_mask, cmap='gray')
    # plt.title('颜色检测')
    # 
    # plt.subplot(2, 3, 3)
    # plt.imshow(edges, cmap='gray')
    # plt.title('Canny边缘检测')
    # 
    # plt.subplot(2, 3, 4)
    # plt.imshow(final_mask, cmap='gray')
    # plt.title('组合结果')
    # 
    # plt.subplot(2, 3, 5)
    # plt.imshow(cv2.cvtColor(result, cv2.COLOR_BGR2RGB))
    # plt.title('最终检测结果')
    # 
    # # 显示带ROI的结果
    # debug_image = result.copy()
    # cv2.polylines(debug_image, [roi_vertices], True, (0, 255, 0), 2)
    # 
    # plt.subplot(2, 3, 6)
    # plt.imshow(cv2.cvtColor(debug_image, cv2.COLOR_BGR2RGB))
    # plt.title('带ROI的结果')
    # 
    # plt.tight_layout()
    # plt.show()

    return result


In [26]:
def process_video(video_path, output_path):
    cap = cv2.VideoCapture(video_path)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (frame_width, frame_height))
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        pr_frame = detect_line(frame)

        if pr_frame is not None:
            out.write(pr_frame)
    if 'cap' in locals():
        cap.release()
    if 'out' in locals():
        out.release()

In [27]:
process_video('./video.mp4','./result.mp4')

[[254 448 324 336]]
[[108 190 197 201]]
[[760 264 822 309]]
[[ 88 193 187 205]]
[[665 213 757 262]]
[[714 231 834 318]]
[[226 492 326 332]]
[[ 46 190 154 199]]
[[704 234 752 259]]
[[662 219 687 220]]
[[102 189 192 200]]
[[710 228 881 352]]
[[ 29 189 117 195]]
[[266 525 299 459]]
[[ 94 193 176 203]]
[[292 473 358 338]]
[[714 229 822 308]]
[[ 17 185 117 190]]
[[243 464 322 338]]
[[663 212 754 259]]
[[120 191 197 201]]
[[586 197 677 223]]
[[197 543 315 354]]
[[264 537 351 359]]
[[ 50 189 190 209]]
[[767 267 833 315]]
[[638 206 743 253]]
[[ 10 187 111 192]]
[[ 12 191  89 195]]
[[196 543 307 365]]
[[262 539 344 371]]
[[ 76 198 159 208]]
[[ 82 194 180 206]]
[[764 266 849 326]]
[[686 230 749 258]]
[[198 542 296 384]]
[[632 216 711 243]]
[[ 66 202 161 215]]
[[721 247 790 284]]
[[671 221 751 250]]
[[  0 194  92 199]]
[[712 246 772 274]]
[[775 276 857 331]]
[[266 536 330 399]]
[[ 69 202 169 216]]
[[696 232 764 258]]
[[ 42 205 141 217]]
[[641 221 705 243]]
[[747 265 814 302]]
[[660 231 741 262]]
